replacements = {
    '\n': ' ',
    '\r': ' ',
    '"': '',
    ":": '',
    "/":'', #TODO probably wh word after / should be removed - to be checked with audio,
    ";": '',
    '`': '',
    'µ': 'u',
    'Ã': 'a',
    'Å': 'a',
    'à': 'a',
    'â': 'a',
    'ó': 'o',
    'ŋ': 'ɲ',
    'ũ': 'u',
    'ǃ': '',
    'ɔ': 'c', #TODO manually figure out what to do
    'ɛ': 'e', #TODO manually figure out what to do
    'ɪ': 'i',
    'ɲ': 'ɲ',
    'ʒ': 'ʒ',
    'ʃ': 'ʃ',
    'ʷ': '',
    'ᵘ': '',
    'ᶦ': '',
    'ạ': 'a',
    '‘': '',
    '’': '',
    '“': '',
    '”': '',
    '…': '',
    'ⁱ': ''
}